# Generated by Django 5.0.6 on 2024-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('item_text', models.TextField(max_length=200, verbose_name='Текст пункта')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
