# Generated by Django 5.0.6 on 2024-09-16 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_calendar_id', models.IntegerField()),
                ('address', models.CharField(max_length=512)),
                ('rooms', models.IntegerField()),
                ('sleeps', models.CharField(max_length=512)),
                ('desc', models.TextField()),
                ('floor', models.IntegerField(blank=True, default=0, null=True)),
                ('humans', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('map_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('map_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('main_photo', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='ApartmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('real_calendar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('map_longitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('map_latitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=512)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'Фото квартиры',
                'verbose_name_plural': 'Фото квартир',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='services',
            field=models.ManyToManyField(to='apartments.apartmentservice'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.city'),
        ),
    ]
