# Generated by Django 5.0.6 on 2024-09-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_view_zoom',
            field=models.IntegerField(default=15),
        ),
    ]
