# Generated by Django 5.0.6 on 2024-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_city_map_view_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
