# Generated by Django 5.0.6 on 2024-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bookinganalytics_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinganalytics',
            name='json_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
