# Generated by Django 5.0.6 on 2024-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('item_text', models.TextField(max_length=200, verbose_name='Текст пункта')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_name',
                 models.CharField(default='Название по умолчанию', max_length=120, verbose_name='Название правила')),
                ('rules_text',
                 models.TextField(default='Текст правила проживания', max_length=1000, verbose_name='Текст правила')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать в списке')),
            ],
            options={
                'verbose_name': 'Правило проживания',
                'verbose_name_plural': 'Правила проживания',
            },
        ),
    ]
