# Generated by Django 5.0.6 on 2024-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningchecklistitem',
            options={'ordering': ('order',), 'verbose_name': 'Пункты уборки', 'verbose_name_plural': 'Пункт уборки'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'ordering': ('order',), 'verbose_name': 'Правило проживания', 'verbose_name_plural': 'Правила проживания'},
        ),
        migrations.AddField(
            model_name='cleaningchecklistitem',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке'),
        ),
        migrations.AddField(
            model_name='cleaningchecklistitem',
            name='item_name',
            field=models.CharField(default='Название по умолчанию', max_length=120, verbose_name='Название пункта'),
        ),
        migrations.AddField(
            model_name='rules',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='cleaningchecklistitem',
            name='item_text',
            field=models.TextField(default='Текст пункта уборки', max_length=200, verbose_name='Текст пункта'),
        ),
        migrations.AlterField(
            model_name='cleaningchecklistitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
    ]
