# Generated by Django 5.0.6 on 2024-09-20 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать в списке')),
                ('city_address_name', models.CharField(default='Адрес достопримечательности', max_length=256, verbose_name='Адрес достопримечательности')),
                ('map_link', models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на карту')),
                ('title', models.CharField(default='Название достопримечательности', max_length=256, verbose_name='Название достопримечательности')),
                ('description', models.TextField(default='Описание достопримечательности', max_length=512, verbose_name='Описание достопримечательности')),
                ('attraction_cite', models.URLField(blank=True, default=None, null=True, verbose_name='Сайт достопримечательности')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('attraction_logo', models.ImageField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apartments.city')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
            },
        ),
    ]
