# Generated by Django 5.0.6 on 2024-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
