# Generated by Django 5.0.6 on 2024-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Правило проживания', 'verbose_name_plural': 'Правила проживания'},
        ),
        migrations.AddField(
            model_name='rules',
            name='rules_name',
            field=models.CharField(default='Название по умолчанию', max_length=120),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rules_text',
            field=models.TextField(default='Текст правила проживания', max_length=1000),
        ),
    ]
