# Generated by Django 5.0.6 on 2024-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rules_options_rules_rules_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rules_name',
            field=models.CharField(default='Название по умолчанию', max_length=120, verbose_name='Название правила'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rules_text',
            field=models.TextField(default='Текст правила проживания', max_length=1000, verbose_name='Текст правила'),
        ),
    ]
