# Generated by Django 5.0.6 on 2024-08-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('salary', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('work_conditions', models.TextField()),
                ('responsibilities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.responsibility')),
            ],
        ),
    ]
