# Generated by Django 5.0.6 on 2024-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Условия работы',
                'verbose_name_plural': 'Условия работы',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Обязанность',
                'verbose_name_plural': 'Обязанности',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать в списке')),
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Название вакансии')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес работы')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('conditions', models.ManyToManyField(blank=True, null=True, to='vacancies.conditions', verbose_name='Условия работы')),
                ('requirements', models.ManyToManyField(blank=True, null=True, to='vacancies.requirements', verbose_name='Требования')),
                ('responsibilities', models.ManyToManyField(blank=True, null=True, to='vacancies.responsibility', verbose_name='Обязанности')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
