# Generated by Django 5.0.6 on 2024-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.ManyToManyField(to='vacancies.responsibility'),
        ),
    ]
