# Generated by Django 5.0.6 on 2024-08-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_vacancy_responsibilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.ManyToManyField(to='vacancies.conditions'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(to='vacancies.requirements'),
        ),
    ]
