# Generated by Django 5.0.6 on 2024-08-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_conditions_requirements_vacancy_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='work_conditions',
        ),
    ]
